"""basic hero

Revision ID: 6eb2faf0bf90
Revises: c02e03389436
Create Date: 2023-12-26 00:11:11.977749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb2faf0bf90'
down_revision: Union[str, None] = 'c02e03389436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_table',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('avatar_file_id', sa.String(length=256), nullable=False),
    sa.Column('nick', sa.String(length=256), nullable=False),
    sa.Column('energy', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_table')
    # ### end Alembic commands ###
