"""owner must not be unique

Revision ID: 2e96aab72211
Revises: 6eb2faf0bf90
Create Date: 2023-12-26 01:26:41.118172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e96aab72211'
down_revision: Union[str, None] = '6eb2faf0bf90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hero_table_owner_id_key', 'hero_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hero_table_owner_id_key', 'hero_table', ['owner_id'])
    # ### end Alembic commands ###
