"""basic tile table

Revision ID: f433de8436c9
Revises: 2e96aab72211
Create Date: 2023-12-27 12:42:59.293766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f433de8436c9'
down_revision: Union[str, None] = '2e96aab72211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_table',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('x', sa.INTEGER(), nullable=True),
    sa.Column('y', sa.INTEGER(), nullable=True),
    sa.Column('_type', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_table')
    # ### end Alembic commands ###
