"""recreate map migration

Revision ID: 5389cc747e77
Revises: 2e96aab72211
Create Date: 2023-12-27 13:37:53.266109

"""
import asyncio
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from map_gen import generate_map

# revision identifiers, used by Alembic.
revision: str = '5389cc747e77'
down_revision: Union[str, None] = '2e96aab72211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_table',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('x', sa.INTEGER(), nullable=True),
    sa.Column('y', sa.INTEGER(), nullable=True),
    sa.Column('_type', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.add_column('hero_table', sa.Column('tile_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_tile_id', 'hero_table', 'map_table', ['tile_id'], ['pk'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tile_id', 'hero_table', type_='foreignkey')
    op.drop_column('hero_table', 'tile_id')
    op.drop_table('map_table')
    # ### end Alembic commands ###
