"""change name user table

Revision ID: c02e03389436
Revises: af4c24c0ee93
Create Date: 2023-12-10 02:04:00.137746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02e03389436'
down_revision: Union[str, None] = 'af4c24c0ee93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('tg_id')
    )
    op.drop_table('User_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_table',
    sa.Column('pk', sa.INTEGER(), server_default=sa.text('nextval(\'"User_table_pk_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('banned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk', name='User_table_pkey'),
    sa.UniqueConstraint('tg_id', name='User_table_tg_id_key')
    )
    op.drop_table('user_table')
    # ### end Alembic commands ###
